using System.ComponentModel.DataAnnotations;

namespace TextSanitizerAPI.Models
{
    public class SensitiveWord
    {
        [Key] // Add this annotation to specify the primary key
              // [DatabaseGenerated(DatabaseGeneratedOption.None)] // Add this annotation to specify that the value will not be generated by the database
        public int Id { get; set; }
        [Required]
        public string Word { get; set; }
    }
}
